Repository tier4/caret_analyze, pull requests merged in 2024-01, with the labels that each got.

#462 chore: mkdocstrings version to avoid 0.24
  mkdocs-requirements.txt
Labels: tag:deploy-docs

#454 docs: fix doc string in `value_object` package
  src/caret_analyze/value_objects/callback.py
  src/caret_analyze/value_objects/executor.py
  src/caret_analyze/value_objects/message_context.py
  src/caret_analyze/value_objects/node.py
  src/caret_analyze/value_objects/node_path.py
  src/caret_analyze/value_objects/path.py
  src/caret_analyze/value_objects/publisher.py
  src/caret_analyze/value_objects/qos.py
  src/caret_analyze/value_objects/service.py
  src/caret_analyze/value_objects/subscription.py
  src/caret_analyze/value_objects/timer.py
  src/caret_analyze/value_objects/variable_passing.py
Labels: documentation, tag:deploy-docs

#466 fix: error with empty records
  src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
Labels: bug
